### ISSUE TITLE
copyright and license violation

### ISSUE THREAD

**Issue by nicolaasuni** [dineshrabara/barcodeAll#5]
This project is using code copied from:
https://github.com/tecnickcom/TCPDF
but all copyright and license terms were removed.
Please immediately delete all the copied code or adapt it to conform the original copyright and license requirements.

Please also note that the code you have copied has now been replaced by another project:
https://github.com/tecnickcom/tc-lib-barcode

Please carefully read the license and act promptly.

**Comment by dineshrabara** [comment]
Dear sir,

it's open source  not my personal use

**Comment by nicolaasuni** [comment]
This is a serious issue and I am asking you to take immediate action.

The options to remedy the infringement are:
1. delete the project - this seems the best option as this project seems not adding anything to the original files.
2. if the license is compatible with GNU-LGPLv3, replace the infringing files with the original ones, or reinstate the original notices (author, copyright, license);
3. delete the infringing files and use the new external library https://github.com/tecnickcom/tc-lib-barcode (originally based on the same code).
